-- MySQL Script generated by MySQL Workbench
-- Wed Oct 30 17:40:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmacy` DEFAULT CHARACTER SET utf8mb3 ;
USE `pharmacy` ;

-- -----------------------------------------------------
-- Table `pharmacy`.`healthnetwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`healthnetwork` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmacy`.`sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`sector` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmacy`.`typepharmacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`typepharmacy` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmacy`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `numberPhone` VARCHAR(20) NOT NULL,
  `nit` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmacy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`user` (
  `id` INT NOT NULL,
  `userName` VARCHAR(60) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `role` VARCHAR(45) NOT NULL,
  `firstLogin` TINYINT NOT NULL DEFAULT '1',
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_person1_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_user_person1`
    FOREIGN KEY (`id`)
    REFERENCES `pharmacy`.`person` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmacy`.`town`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`town` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmacy`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`zona` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  `idTown` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zona_town1_idx` (`idTown` ASC) VISIBLE,
  CONSTRAINT `fk_zona_town1`
    FOREIGN KEY (`idTown`)
    REFERENCES `pharmacy`.`town` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmacy`.`pharmacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`pharmacy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `latitude` VARCHAR(100) NOT NULL,
  `longitude` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `codeZona` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  `idSector` SMALLINT NOT NULL,
  `idTypePharmacy` SMALLINT NOT NULL,
  `idZona` SMALLINT NOT NULL,
  `idHealthNetwork` SMALLINT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pharmacy_sector1_idx` (`idSector` ASC) VISIBLE,
  INDEX `fk_pharmacy_typePharmacy1_idx` (`idTypePharmacy` ASC) VISIBLE,
  INDEX `fk_pharmacy_zona1_idx` (`idZona` ASC) VISIBLE,
  INDEX `fk_pharmacy_healthNetwork1_idx` (`idHealthNetwork` ASC) VISIBLE,
  INDEX `fk_pharmacy_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_pharmacy_healthNetwork1`
    FOREIGN KEY (`idHealthNetwork`)
    REFERENCES `pharmacy`.`healthnetwork` (`id`),
  CONSTRAINT `fk_pharmacy_sector1`
    FOREIGN KEY (`idSector`)
    REFERENCES `pharmacy`.`sector` (`id`),
  CONSTRAINT `fk_pharmacy_typePharmacy1`
    FOREIGN KEY (`idTypePharmacy`)
    REFERENCES `pharmacy`.`typepharmacy` (`id`),
  CONSTRAINT `fk_pharmacy_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `pharmacy`.`user` (`id`),
  CONSTRAINT `fk_pharmacy_zona1`
    FOREIGN KEY (`idZona`)
    REFERENCES `pharmacy`.`zona` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmacy`.`controlledmedications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`controlledmedications` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `typeMedicine` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  `idPharmacy` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_controlledMedications_pharmacy1_idx` (`idPharmacy` ASC) VISIBLE,
  CONSTRAINT `fk_controlledMedications_pharmacy1`
    FOREIGN KEY (`idPharmacy`)
    REFERENCES `pharmacy`.`pharmacy` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pharmacy`.`openinghours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`openinghours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day` VARCHAR(45) NOT NULL,
  `openTime` VARCHAR(45) NULL DEFAULT NULL,
  `closeTime` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `registerDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Update Date` TIMESTAMP NULL DEFAULT NULL,
  `idPharmacy` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_openingHours_pharmacy1_idx` (`idPharmacy` ASC) VISIBLE,
  CONSTRAINT `fk_openingHours_pharmacy1`
    FOREIGN KEY (`idPharmacy`)
    REFERENCES `pharmacy`.`pharmacy` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
